### ISSUE TITLE
Setting SSH_USER=root is ignored silently.

### ISSUE THREAD

**Issue by akvadrako** [jdeathe/centos-ssh#261]
Currently it silently ignores the option.

**Comment by jdeathe** [comment]
@akvadrako Yes! This is intentional; you cannot add a root user as it already exists.

There is validation on all the value to prevent invalid usernames too.
- https://github.com/jdeathe/centos-ssh/blob/centos-7-develop/usr/sbin/sshd-bootstrap#L70

It should be simple enough to fail with an error message so I can look into adding that in in a future release.

**Comment by jdeathe** [comment]
Should also update the README.md regarding accepted values for Environment Variables.
